spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: backend-service
          uri: http://localhost:9999
          predicates:
            - Path=/backend/**
    #          filters:
    #            - name: RequestRateLimiter
    #              args:
    #                key-resolver: "#{@userKeyResolver}"
    #                redis-rate-limiter.replenishRate: 1
    #                redis-rate-limiter.burstCapacity: 1
    #                redis-rate-limiter.requestedTokens: 1
    function:
      definition: consumer;producer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        producer-out-0:
          destination: first-topic
        consumer-in-0:
          destination: first-topic


management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE